- name: Copy Logstash Conf
  copy:
   src: logstash.conf
   dest: /etc/logstash/conf.d/logstash.conf
   
- name: Stop Logstash
  systemd:
   name: logstash
   state: stopped
  
- name: Waits for port 5044 to Close
  wait_for:
    port: 5044
    delay: 15
    state: stopped