- name: Copy Logstash Conf
  copy:
   src: logstash.conf
   dest: /etc/logstash/conf.d/logstash.conf
   
- name: Restart Logstash
  systemd:
   name: logstash
   state: restarted
  
- name: Waits for port 5044 to Close
  wait_for:
    port: 5044
    delay: 10
    state: drained