- name: loops
  hosts: localhost
  tasks:
   - name: Print User detils
     debug:
      msg: Heloo {{item}}
     loop:
      - dheeraj
      - sai
   - name: printuser deatils from map
     debug:
      msg: Heloo {{item.name}}, welocm {{item.course}}
     loop: 
      - { name: john, course: swa }
      - { name: king, course: dfjhs}