- name: RoboShop Setup Frontend
  hosts: FRONTEND
  tags:
   - frontend
  become: yes
  roles:
   - frontend
  
- name: RoboShop Setup Mongodb
  hosts: MONGODB
  tags:
   - mongodb
  become: yes
  roles:
   - mongodb
  
- name: RoboShop Setup Catalogue
  hosts: CATALOGUE
  tags:
   - catalogue
  become: yes
  roles:
   - catalogue
  
- name: RoboShop Setup Redis
  hosts: REDIS
  tags:
   - redis
  become: yes
  roles:
   - redis
  
- name: RoboShop Setup User
  hosts: USER
  tags:
   - user
  become: yes
  roles:
   - user
  
- name: RoboShop Setup Cart
  hosts: CART
  tags:
   - cart
  become: yes
  roles:
   - cart
  
- name: RoboShop Setup Mysql
  hosts: MYSQL
  tags:
   - mysql
  become: yes
  roles:
   - mysql
 
- name: RoboShop Setup Shipping
  hosts: SHIPPING
  tags:
   - shipping
  become: yes
  roles:
   - shipping
  
- name: RoboShop Setup RabbitMQ
  hosts: RABBITMQ
  tags: rabbitmq
 become: yes
 roles:
   - rabbitmq
 
- name: RoboShop Setup Payment
  hosts: PAYMENT
  tags:
   - payment
  become: yes
  roles:
   - payment
  
 