- name: RoboShop Setup Frontend
  hosts: FRONTEND
  tags:
   - frontend
  roles:
   - frontend
  
- name: RoboShop Setup Mongodb
  hosts: MONGODB
  tags:
   - mongodb
  roles:
   - mongodb
  
- name: RoboShop Setup Catalogue
  hosts: CATALOGUE
  tags:
   - catalogue
  roles:
   - catalogue
  
- name: RoboShop Setup Redis
  hosts: REDIS
  tags:
   - redis
  roles:
   - redis
  
- name: RoboShop Setup User
  hosts: USER
  tags:
   - user
  roles:
   - user
  
- name: RoboShop Setup Cart
  hosts: CART
  tags:
   - cart
  roles:
   - cart
  
- name: RoboShop Setup Mysql
  hosts: MYSQL
   tags:
   - mysql
  roles:
   - mysql
 
- name: RoboShop Setup Shipping
  hosts: SHIPPING
  tags:
   - shipping
  roles:
   - shipping
  
- name: RoboShop Setup RabbitMQ
  hosts: RABBITMQ
   tags:
   - rabbitmq
  roles:
   - rabbitmq
 
- name: RoboShop Setup Payment
  hosts: PAYMENT
  tags:
   - payment
  roles:
   - payment
  
 