- name: Install NGINX
  yum:
    name: nginx
    state: present
    
- name: Download HTML file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes
  
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
    
- name: Copy file from one Module to other
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes
    
- name: Copying Roboshop Conf file
  ansible.builtin.copy:
    src: roboshop.conf
    dest:  /etc/nginx/default.d/roboshop.conf
  notify: Restart NGINX
   
- name: Restart NGINX
  systemd:
   name: nginx
   state: started
   enabled: yes
   
- name: Include Node_Exporter
  include_role:
   name: common
   tasks_from: node_exporter
   
- name: Include Filebeat
  include_role:
   name: common
   tasks_from: filebeat
  vars:
   OUTPUT_TO: logstash
   NGINX: true