- name: Install erlang
  yum:
   name: 
    - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
   state: present
   
- name: Set Up Yum Repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
  
- name: Install Rabbit MQ server
  yum: 
   name: rabbitmq-server
   state: present
   
- name: Start Rabbit MQ Server
  systemd:
   name: rabbitmq-server
   state: started
   enabled: yes
   
- name: Creating user & setting Up permission
  community.rabbitmq.rabbitmq_user:
   user: roboshop
   password: roboshop123
   vhost: /
   configure_priv: .*
   read_priv: .*
   write_priv: .*
   state: present
   tags: administrator
  