- name: Installing Node JS
  yum:
   name:
    - nodejs
    - gcc-c++
    - npm
   state: present
 
- name: Adding Roboshop as User
  user:
   name: roboshop
   
- name: Download Catalogue archive
  ansible.builtin.unarchive:
   src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
   dest: /tmp
   remote_src: yes
   
- name: Remove the catalogue old content
  ansible.builtin.file:
   path: /home/roboshop/catalogue
   state: absent
   
- name: Copying the catalogue module
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop
    
- name: Install npm based on package.json.
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop
  
- name: Restarting Catalogue
  systemd:
   name: catalogue
   state: restarted
   enabled: yes
   daemon_reload: yes