- name: Installing Node JS
  yum:
   name:
    - nodejs
    - gcc-c++
   state: present
 
- name: Adding Roboshop as User
  user:
   name: 
    - roboshop
   
- name: Download Catalogue archive
  ansible.builtin.unarchive:
   src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
   dest: /tmp
   remote_src: yes
   
- name: Remove the catalogue old content
  ansible.builtin.file:
   path: /home/roboshop/catalogue
   
- name: Copying the catalogue module
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    