- name: Update Prometheus Config
  template:
   src: "{{item}}.yml"
   dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - records
    - alerts
 
- name: Restart Prometheus
  systemd:
   name: prometheus
   state: restarted
   enabled: yes
   
- name: Update Alertmanager Config
  template:
   src: "{{item}}.yml"
   dest: /opt/alertmanager/{{item}}.yml
  loop:
    - alertmanager
 
- name: Restart Alertmanager
  systemd:
   name: alertmanager
   state: restarted
   enabled: yes