- name: Update Prometheus Config
  template:
   src: "{{item}}.yml"
   dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - records
    - alerts
 
- name: Restart Prometheus
  systemd:
   name: prometheus
   state: restarted
   enabled: yes