- name: Update Prometheus Config
  templates:
   src: prometheus.yml
   dest: /opt/prometheus/prometheus.yml
   
- name: Restart Prometheus
  systemd:
   name: prometheus
   state: restarted
   enabled: yes