- name: Adding Roboshop as User
  user:
    name: roboshop
  register: USERDETAILS
  when: APP_TYPE == "backend"

- name: Remove the {{COMPONENT}} old content
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent

- name: Creating APP Directory for backend
  file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "backend"
  become_user: roboshop

- name: Creating APP Directory for frontend
  file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "frontend"

- name: copy AZ Module
  copy:
   src: az.repo
   dest: /etc/yum.repos.d/az.repo

- name: Install AZ CLI
  yum:
    name:
    - azure-cli
    - libicu
    state: present

- name: Install AZ DevOps Extension
  shell: az extension add --name azure-devops

- name: Auth to AZ DevOps
  shell: echo {{PAT}} | az devops login

- name: Download Artifacts
  shell: az artifacts universal download --organization https://dev.azure.com/saidheeraj52056/ --project="RoboShop" --scope project --feed DevOps --name {{COMPONENT}} --version {{APP_VERSION}} --path .
  args:
    chdir: "{{APP_PATH}}"

- name: stop
  shell: exit 1

