- name: Adding Roboshop as User
  user:
    name: roboshop
  register: USERDETAILS
  when: APP_TYPE == "backend"

- name: Download {{COMPONENT}} archive
  get_url:
    url: http://172.31.13.236:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    username: admin
    password: admin

- name: Remove the {{COMPONENT}} old content
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent

- name: Creating APP Directory for backend
  file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "backend"
  become_user: roboshop

- name: Creating APP Directory for frontend
  file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "frontend"

- name: Extract {{COMPONENT}} archive for backend
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_PATH}}"
    remote_src: yes
  when: APP_TYPE == "backend"
  become_user: roboshop

- name: Extract {{COMPONENT}} archive for frontend
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_PATH}}"
    remote_src: yes
  when: APP_TYPE == "frontend"


#- name: Copying the {{COMPONENT}} module
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: "{{APP_PATH}}/"
#    remote_src: yes
#    owner: roboshop
#    group: roboshop
#  when: APP_TYPE == "backend"
#
#- name: Copying the {{COMPONENT}} module
#  ansible.builtin.copy:
#    src: /tmp/frontend-main/static/
#    dest: "{{APP_PATH}}/"
#    remote_src: yes
#  when: APP_TYPE == "frontend"