- name: Install Maven
  yum:
   name: maven
   state: present
   
- name: Adding User Roboshop
  user:
   name: roboshop
   
- name: Download
  include_tasks: download.yml
  
- name: Make Maven Package
  shell:  mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/shipping
    
- name: systemd
  include_tasks: systemd.yml
  
- name: Node Exporter
  include_tasks: node_exporter.yml
  
- name: Filebeat Installing
  include_tasks: filebeat.yml
  