- name: Set up Rsyslog
  template:
   src: rsyslog.conf
   dest: /etc/rsyslog.d/roboshop.conf
   
- name: Restart Rsyslog
  systemd:
   name: rsyslog
   state: restarted
   
- name: Install Maven
  yum:
   name: maven
   state: present
   
- name: Adding User Roboshop
  user:
   name: roboshop
   
- name: Download
  include_tasks: download.yml
  vars:
    APP_PATH: /home/roboshop/{{COMPONENT}}
  
- name: Make Maven Package
  shell:  mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/shipping
    
- name: systemd
  include_tasks: systemd.yml
  
- name: Node Exporter
  include_tasks: node_exporter.yml
  
- name: Filebeat Installing
  include_tasks: filebeat.yml
  vars:
   OUTPUT_TO: logstash
   JAVA: true
  