- name: Installing Node JS
  yum:
   name:
    - nodejs
    - make
    - gcc-c++
   state: present
 
- name: Adding Roboshop as User
  user:
   name: roboshop
   
- name: Download {{COMPONENT}} archive
  ansible.builtin.unarchive:
   src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
   dest: /tmp
   remote_src: yes
   
- name: Remove the {{COMPONENT}} old content
  ansible.builtin.file:
   path: /home/roboshop/{{COMPONENT}}
   state: absent
   
- name: Copying the {{COMPONENT}} module
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop
    
- name: Install npm based on package.json.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop
  
- name: Copying the {{COMPONENT}} service file
  copy:
   src: systemd.service
   dest: /etc/systemd/system/{{COMPONENT}}.service
  
- name: Restarting {{COMPONENT}}
  systemd:
   name: {{COMPONENT}}
   state: restarted
   enabled: yes
   daemon_reload: yes