- name: Set up Rsyslog
  template:
   src: rsyslog.conf
   dest: /etc/rsyslog.d/roboshop.conf
   
- name: Restart Rsyslog
  systemd:
   name: rsyslog
   state: restarted
   
- name: Installing Node JS
  yum:
   name:
    - nodejs
    - make
    - gcc-c++
   state: present
 
- name: Download
  include_tasks: download.yml
  vars:
    APP_PATH: /home/roboshop/{{COMPONENT}}

- name: Install NodeJS Dependencies
  npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop
  
- name: Systemd
  include_tasks: systemd.yml
  
- name: Node Exporter Installing
  include_tasks: node_exporter.yml
  
- name: Filebeat Installing
  include_tasks: filebeat.yml
  vars:
   OUTPUT_TO: elasticsearch