- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/node_exporter
    state: directory
    
- name: Download Node Exporter
  unarchive:
   src: https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
   dest: /opt/node_exporter
   remote_src: yes
