- name: Set up Rsyslog
  template:
   src: rsyslog.conf
   dest: /etc/rsyslog.d/roboshop.conf
   
- name: Restart Rsyslog
  systemd:
   name: rsyslog
   state: restarted
   
- name: Install Python
  yum:
   name:
    - python36
    - gcc
    - python3-devel
    
- name: Doing User adding tasks
  include_tasks: download.yml
  vars:
    APP_PATH: /home/roboshop/{{COMPONENT}}
  
- name: Install Python Dependencies
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3
    
- name: Changing uid in the Payment.ini file
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{USERDETAILS.uid}}
    
- name: Changing gid in the Payment.ini file
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{USERDETAILS.group}}
    
- name: Making system restart from common tasks
  include_tasks: systemd.yml
  
- name: Node Exporter Installing
  include_tasks: node_exporter.yml
  
- name: Filebeat Installing
  include_tasks: filebeat.yml
  vars:
   OUTPUT_TO: logstash
   PYTHON: true