- name: Copying the {{COMPONENT}} service file
  template:
   src: systemd.service
   dest: /etc/systemd/system/{{COMPONENT}}.service
  
- name: Restarting {{COMPONENT}}
  systemd:
   name: "{{COMPONENT}}"
   state: restarted
   enabled: yes
   daemon_reload: yes