groups:
- name: Roboshop
  rules:
  - alert: HighCPUUsage
    expr: cpu_usage_in_percentage > 50
    for: 1m
    labels:
      severity: warning
    annotations:
     summary: "HighCPU on {%raw%}{{ $labels.tagName }}{%endraw%}"

- name: Roboshop Service Monitering
  rules:
  - alert: ServicesDown
    expr: roboshop_service_monitering == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%}"Service {{ $labels.name }}  Down on {{ $labels.tagName }} Server"{%endraw%}