groups:
- name: Roboshop
  rules:
  - alert: HighCPUUsage
    expr: cpu_usage_in_percentage > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: HighCPUUsage on {%raw%}{{ $labels.tagName }}{%endraw%}
      
  - alert: CatalogueServicesDown
    expr: roboshop_service_monitering == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%}"Service {{ $labels.name }} is Down on {{ $labels.tagName }}"{%endraw%}
    