groups:
- name: Roboshop
  rules:
  - alert: HighCPUUsage
    expr: cpu_usage_in_percentage > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: HighCPUUsage on {%raw%}{{ $labels.tagName }}{%endraw%}
      
- name: Services
  rules:
  - alert: FrontendServicesDown
    expr: node_systemd_unit_state{name="nginx.service",tagName="frontend",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}
      
  - alert: CatalogueServicesDown
    expr: node_systemd_unit_state{name="catalogue.service",tagName="catalogue",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}
      
  - alert: UserServiceDown
    expr: node_systemd_unit_state{name="user.service",tagName="user",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}
      
  - alert: CartServicesDown
    expr: node_systemd_unit_state{name="cart.service",tagName="cart",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}
      
  - alert: ShippingServicesDown
    expr: node_systemd_unit_state{name="shipping.service",tagName="shipping",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}
      
  - alert: PaymentServicesDown
    expr: node_systemd_unit_state{name="payment.service",tagName="payment",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: {%raw%} "{{ $labels.name }}" is Down on {{ $labels.tagName }}{%endraw%}