global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'
#   - 'email'
  
  
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#prom-alerts'
        send_resolved: true
#   - name: email
#     email_configs:
#       - to: sai.dheeraj.52056@gmail.com
#         from: sai.dheeraj.52056@gmail.com
#         smarthost: email-smtp.us-east-1.amazonaws.com:587
#         auth_username: AKIAQJM7CLNWESZMKCNO
#         auth_password: BMFk5fX5TK8jL8TLV9FlGla+w1nq9C3PQ+C/+wahXskk
#         require_tls: yes
#         send_resolved: true
        
  
     
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']